<?php

/**
 * @file
 *  theme.inc
 * Dummy
 */

/**
 * Dummy function
 */
function theme_batire_search_ui_footer_search_block_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_header_search_block_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_footer_search_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_header_search_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_search_results_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_search_results_filters_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_search_results_info_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_advanced_search_page_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function batire_search_ui_advanced_search_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_popup_save_search_content($search_id, $r_search_id) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_save_search_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_popup_register_docs_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_document_pager_content($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_results_back_link($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_search_ui_print_results($print) {
  return 'dummy';
}