<?php

/**
 * @file
 *  theme.inc
 * Dummy
 */

/**
 * Dummy function
 */
function theme_batire_user_searches_popup_alert($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_searches_create_alert_form($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_create_send_mail_form($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_send_mail_group_form($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_searches_popup_report($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_searches_popup_save_search($form, $action) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_searches_save_search_form($form) {
  return 'dummy';
}
