<?php

/**
 * Implementation of hook_menu().
 */
function batire_gc_menu() {
  $items = array();

  $items['admin/batire-site/gc'] = array(
    'title' => 'Parametres du GC',
    'position' => 'left',
    'weight' => 3,
    'description' => 'Parametres du GC',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer batire configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}
