<?php

/**
 * @file
 * Dummy
 */

/**
 * Dummy function
 */
function theme_batire_user_docs_annotations($total_cnt, $personel_list, $shared_list, $multipost) {
  return $total_cnt;
}

/**
 * Dummy function
 */
function theme_batire_user_docs_annotation_item($nid, $date, $text) {
  return $nid;
}

/**
 * Dummy function
 */
function theme_batire_popup_report($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_popup_download($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_popup_show_pdf($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_popup_print($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_popup_create_folder($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_popup_remove_document($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_form_remove_document($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_popup_move_rename_folder_content($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_popup_move_document($nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_form_move_document($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_my_account_widget_folders($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_widget_folders_item($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_register_document_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_folder_icon($folder_data, $folder_count, $text) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_popup_classify_content($form, $nids) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_form_download_pdf_doc($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function batire_user_docs_print_form_content($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_print_anno_list($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_print_annotation_render($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_print_references_render($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_print_image($print) {
  return 'dummy';
}