<?php
/**
 * @file
 * Dummy
 */

/**
 * Dummy function
 */
function theme_batire_user_popup_login_content() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_recovery_password() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_where_to_find() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_recovery_password_form() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_thank_you($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_subscription_page($content, $title, $subtitle, $type) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_docs_infobar($shared, $folders, $anno_cnt, $alert) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_activate_abonement($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_activate_abonement_s2($form, $full_name) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_activate_abonement_success() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_activate_abonement_success_free($date) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_popup_activate_abonement_s2_form($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_list_accounts($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_list_account($profile, $cnt) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_group_members($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_group_member($profile) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_abonement_date($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_detail_abonnement($content) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_detail_abonnement_form($form) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_user_transform_abonnement_form($form) {
  return 'dummy';
}
