<?php

/**
 * @file
 * Dummy file
 */

/**
 * Dummy function
 */
function theme_batire_link($text, $path, $options) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_top($site_slogan, $menu) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_header($site_logo, $login_block) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_summary_content() {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_header_login_form($login_block) {
  return 'dummy';
}

function theme_batire_site_gc_user_header_block($login_block) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_footer_auth($title_left, $menu_left, $menu_right) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_footer_notauth($title_left, $menu_left, $title_right, $menu_right, $is_last) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_my_account_menu($menu) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_user_header($profile) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_my_account_home_block($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_help_link($msg, $span) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_sitemap($data) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_item_list($items, $attributes, $div, $array) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_pdf_item_list($items, $attributes, $div, $array) {
  return 'dummy';
}

/**
 * Dummy function
 */
function theme_batire_site_popup_bad_reference($nids) {
  return 'dummy';
}


/**
 * Dummy function
 */
function theme_batire_site_bad_reference_form($form, $nid) {
  return 'dummy';
}

